spring:
  datasource:
    url: jdbc:mysql://qwe.szvone.cn:3306/mdkj?useUnicode=true&characterEncoding=utf8
    username: mdkj
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

logging:
  level:
    cn:
      szvone:
        mdkj:
          dao:
            debug

