spring:
  datasource:
    url: jdbc:mysql://148.70.101.149:3306/mdkj01?useUnicode=true&characterEncoding=utf8
    username: mdkj01
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

logging:
  level:
    cn:
      szvone:
        mdkj:
          dao:
            debug

